package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class UserService {

	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	
	public Iterable<User> getAll() {
		return userRepository.findAll();
	}
	
	public void save(User user){
		userRepository.save(user);
	}
}
